//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverydaySolutions.C45.C45Interop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class C45Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal C45Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverydaySolutions.C45.C45Interop.C45Exceptions", typeof(C45Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add test cases..
        /// </summary>
        internal static string CASES_NOT_ADDED {
            get {
                return ResourceManager.GetString("CASES_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file not found. Created a new one..
        /// </summary>
        internal static string CONFIG_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("CONFIG_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete attribute / probability count mismatch..
        /// </summary>
        internal static string DISCRETE_COUNT_MISMATCH {
            get {
                return ResourceManager.GetString("DISCRETE_COUNT_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is empty.
        /// </summary>
        internal static string EMPTY_FILE {
            get {
                return ResourceManager.GetString("EMPTY_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on saving the xml document.
        /// </summary>
        internal static string ERROR_SAVING_XML_FILE {
            get {
                return ResourceManager.GetString("ERROR_SAVING_XML_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filename set..
        /// </summary>
        internal static string NO_FILENAME_SET {
            get {
                return ResourceManager.GetString("NO_FILENAME_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing .names file..
        /// </summary>
        internal static string PARSE_NAMES_ERROR {
            get {
                return ResourceManager.GetString("PARSE_NAMES_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics failure..
        /// </summary>
        internal static string STATISTICS_FAILURE {
            get {
                return ResourceManager.GetString("STATISTICS_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decision tree could not be generated..
        /// </summary>
        internal static string TREE_NOT_GENERATED {
            get {
                return ResourceManager.GetString("TREE_NOT_GENERATED", resourceCulture);
            }
        }
    }
}
